### ISSUE TITLE
100% cpu usage (1 core) until restarted

### ISSUE THREAD

**Issue by IncognitoCore** [linuxserver/docker-jackett#34]
| Host OS | LimeTech unRAID 6.3.5 |
| Template | [screenshot link](https://www.dropbox.com/s/hw33p0tp8aqvgkb/Screen%20Shot%202017-11-01%20at%2012.42.06.png?dl=0) |
| Docker log | [log link](https://www.dropbox.com/s/fckgc819ndadqx5/log.txt?dl=0) |

I'm seeing 100% cpu usage (which is 100% of the total 400%, since I have 4 cores) when Jackett is running for a while. I'm seeing this issue since I've installed Jackett (4-5 months or something). It happens around twice a week I think.

A friend of mine is also seeing this issue, so it's not limitted to my setup.

The only way to stop Jackett from using up to 100% cpu is to restart the docker container in the unRAID GUI. I've also found out that when its running at 100% cpu, other dockers, like Transmission, cannot find leechers/peers anymore, so Jackett is really hanging.

**Comment by rosshettel** [comment]
I've run into this as well

**Comment by Redsandro** [comment]
Not sure if this is docker, mono, or jackett related. But I've run into this as well.

See https://github.com/Jackett/Jackett/issues/2198

**Comment by rosshettel** [comment]
Thanks, I'll follow there too

**Comment by IncognitoCore** [comment]
It seems like I have this problem more often now. Happened once every two weeks before, now it's happening every 1-2 days here...

**Comment by vSh1ny** [comment]
Same here. It's not 100%, though, more like around ~80%, but still pretty much high.
Image attached: jackett resource consumption before and after container reboot.
<details><summary>Spoiler</summary><p><img src="https://user-images.githubusercontent.com/1835021/34081578-ad1e7ab0-e35f-11e7-825b-bd551abded0d.png ">
</p></details>
Perhaps not related (or is it?), but I notice similar behavior with Sonarr container by linuxserver every once in a while as well.

**Comment by rosshettel** [comment]
Someone posted a suggestion in https://github.com/Jackett/Jackett/issues/2198 to try turning off the auto update feature within Jackett, as that might be the cause

**Comment by kaso17** [comment]
I'm not sure about the init system used by the docker container.
Any chance that it there's something which will try to automatically restart jackett if it crashes?
e.g. system.d with Restart=always?

**Comment by vSh1ny** [comment]
@rosshettel Thank you! Turned the auto update off, haven't noticed Jackett misbehaving since then.
@kaso17 Typically, that problem is solved with a supervisor like S6 Overlay within a container. Jackett is being started via a [service script](https://github.com/linuxserver/docker-jackett/blob/master/root/etc/services.d/jackett/run) using S6's framework.

**Comment by kaso17** [comment]
I assume S6 is automatically restarting it then. You might want to add "--NoRestart" to the arguments to prevent the jackett updater from restarting jackett.

**Comment by IncognitoCore** [comment]
Turning off auto update did solve the issue for me as well (I've not seen cpu issues in the last 3 weeks).

**Comment by Zuescho** [comment]
Just noticed the same Problem, will try to turn auto updates off and report back if it fixed it for me.

**Comment by GregaBlatnik** [comment]
I've had auto-update within Jackett turned off always, but still get this issue every few days.. For now, I just go into UnRAID to check once every few days and restart it if necessary, but I wish this would be resolved..

**Comment by aSaltyPirate** [comment]
None of the other solutions were working for me, and then I found that the user I had running Jackett via systemd only had read and execute privileges, not write privileges for the directory the Jackett files were located. I'm no expert but if I had to guess, even though I turned auto update off it was trying to update but failed since it didn't have write permissions to it's own directory.
